### PR TITLE
Fix the registerRegEx problem.

### PR DESCRIPTION
**Pull request by long-woo**
Hi, I'm sorry that there was a problem with the last PR (#18). During the test in the project, it was found that some network requests were always in the `pending` state, and the browser would be stuck. Now we have modified the regular rule again and passed the test. Please merge it again, thank you!

### CODE REVIEW

**Comment by guybedford** [comment]
@long-woo would you be interested in publish access for npm?

**Comment by long-woo** [comment]
Yes, I would.

**Comment by guybedford** [comment]
Sure, what's your npm username?

**Comment by long-woo** [comment]
long.woo

**Comment by guybedford** [comment]
You should have an invite, feel free to publish a release.

**Comment by long-woo** [comment]
Thank you!Invitation accepted.

**Pull request merged**
