### PR TITLE
fix: registerRegEx regex may not start with System.register

### LINKED ISSUE #16: `registerRegEx` regex may not start with `System.register`.
Hi! The file of `systemjs` generated by `vite build` https://demowww.yanzhiquan.net/footer/index.js.

### PR DESCRIPTION
**Pull request by long-woo**
fix #16

### CODE REVIEW

**Comment by guybedford** [comment]
Thanks, makes sense.

**Comment by guybedford** [comment]
@long-woo do you have any interest in assisting with maintaining here? I can run a release, but Babel also needs to be updated as well ideally etc.

**Comment by long-woo** [comment]
Thanks for the trust, I can maintain it

**Comment by guybedford** [comment]
@long-woo thank you, you should have a maintainer invite for the repo now. Just let me know when you'd like to publish to npm and I can assist with that / give you npm access as well.

**Comment by long-woo** [comment]
Okay, thank you

**Pull request merged**
